### ISSUE TITLE
Pipeline doesn't build the right path to the vep cache files

### ISSUE THREAD

**Issue by nschcolnicov** [nf-core/rnavar#122]
### Description of the bug

If running a command that uses the VEP cache files from "s3://annotation-cache/vep_cache" it fails to build the right path and raises this error:
Files within --vep_cache invalid. Make sure there is a directory named caenorhabditis_elegans/110_WBcel235 in s3://annotation-cache/vep_cache/.
https://nf-co.re/sarek/usage#how-to-customise-snpeff-and-vep-annotation
It also fails for other genomes:
Files within --vep_cache invalid. Make sure there is a directory named homo_sapiens/110_GRCh38 in s3://annotation-cache/vep_cache/.
https://nf-co.re/sarek/usage#how-to-customise-snpeff-and-vep-annotation

Both of this files exist, but the path is not properly built:
aws s3 ls s3://annotation-cache/vep_cache/
                           PRE 102_GRCm38/
                           PRE 108_GRCh38/
                           PRE 108_WBcel235/
                           PRE 109_GRCh38/
                           PRE 109_WBcel235/
                           PRE 110_GRCh37/
                           PRE 110_GRCh38/
                           PRE 110_WBcel235/

### Command used and terminal output

```console
For the frist error:
nextflow run ../../main.nf -profile bi,cluster --annotate_tools merge --outdir . -c config.config 

For the second error:
nextflow run ../../main.nf -profile bi,cluster --outdir . --annotate_tools merge --input https://raw.githubusercontent.com/nf-core/test-datasets/rnavar/samplesheet/v1.0/samplesheet_full.csv -c ../config.config
```

### Relevant files

First config.config file defines necesary reference files for running a WBcel235 sample
Second config.config file defines necesary reference files for running GRCh38 sample

### System information

dev branch

**Comment by bounlu** [comment]
Please see my [PR](https://github.com/nf-core/rnavar/pull/106) for the fix.

**Comment by maxulysse** [comment]
This should now be fixed, sorry for the issues
