### ISSUE TITLE
GFF to GTF conversion is ignored, GTF is required!

### ISSUE THREAD

**Issue by m3hdad** [nf-core/rnavar#21]
### Description of the bug

Even though GFF conversion to GTF has been implemented in in `GFFREAD` process, the pipeline requires a GTF file to proceed!

**Comment by praveenraj2018** [comment]
Have you tried passing a GFF file, without a GTF? The pipeline need one of the files - either a GTF or a GFF.

`No GTF or GFF3 annotation specified! The pipeline requires at least one of these files.`

**Comment by m3hdad** [comment]
When I pass the GTF file the pipeline proceeds as expected. But when I pass a GFF file, the pipeline exists with an error asking for GTF file.


> Have you tried passing a GFF file, without a GTF? The pipeline need one of the files - either a GTF or a GFF.
> 
> `No GTF or GFF3 annotation specified! The pipeline requires at least one of these files.`
